// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials
  // Generate this file with credentials with the FlutterFire CLI
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCyH74N-7AwadIwqtRrIAzrNP6g5Hhcemk",
    authDomain: "posilife-87935.firebaseapp.com",
    projectId: "posilife-87935",
    storageBucket: "posilife-87935.appspot.com",
    messagingSenderId: "558771804661",
    appId: "1:558771804661:web:ba62039fcfdc621c47e8bc",
    measurementId: "G-NTN14B6763"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxAcNrrOy_0hrtqj2FcKvqGJLp5n3GS5Q',
    appId: 'posilife-87935',
    messagingSenderId: '',
    projectId: 'posilife-87935',
    storageBucket: 'flutterfire-ui-codelab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxAcNrrOy_0hrtqj2FcKvqGJLp5n3GS5Q',
    appId: 'posilife-87935',
    messagingSenderId: '',
    projectId: 'flutterfire-ui-codelab',
    storageBucket: 'flutterfire-ui-codelab.appspot.com',
    iosClientId: 'IOS CLIENT ID',
    iosBundleId: 'com.example.BUNDLE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxAcNrrOy_0hrtqj2FcKvqGJLp5n3GS5Q',
    appId: 'posilife-87935',
    messagingSenderId: '',
    projectId: 'flutterfire-ui-codelab',
    storageBucket: 'flutterfire-ui-codelab.appspot.com',
    iosClientId: 'IOS CLIENT ID',
    iosBundleId: 'com.example.BUNDLE',
  );
}
