name: complete
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_ui_auth: ^1.9.0
  firebase_ui_oauth_google: ^1.2.12
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  fitbitter: ^2.0.2
  shared_preferences: ^2.2.2
  percent_indicator: ^4.2.3
  table_calendar: ^3.0.9
  fl_chart: ^0.36.0
  cloud_firestore: ^4.13.3
  flutter_local_notifications: ^8.2.0
  timezone: ^0.8.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
